apiVersion: v1
kind: PersistentVolume
metadata:
  creationTimestamp: null
  finalizers:
    - kubernetes.io/pv-protection
  name: local-host-sample
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /mnt/local-sample
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
status: {}