apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2019-12-12T03:33:35Z"
  name: mongo-nodeport
spec:
  ports:
    - name: 27017tcp300001
      nodePort: 30000
      port: 27017
      protocol: TCP
      targetPort: 27017
  selector:
    workload.user.cattle.io/workloadselector: deployment-josmo-mongo
  sessionAffinity: None
  type: NodePort