version: '3'
services:
  dev:
    build: .
    depends_on: [vault]
    command: npm run dev
    volumes:
      - ./:/usr/src/app
    environment:
    - PORT=$PORT
    ports:
      - 3000:$PORT
  vault:
    image: vault:1.4.1
    command: server -dev
    cap_add:
      - IPC_LOCK
    environment:
      - 'VAULT_LOCAL_CONFIG={"ui":true}'
      - VAULT_DEV_ROOT_TOKEN_ID=root
    ports:
      - 8200:8200
